
import javax.swing.DefaultButtonModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sedat
 */ 
public class GlassOperations extends javax.swing.JFrame {
    StokIslemleri islem = new StokIslemleri();
    DatabaseTable islem2 = new DatabaseTable();
    /**
     * Creates new form GlassOperations
     */
    public GlassOperations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        message_box = new javax.swing.JLabel();
        tf_purchase = new javax.swing.JTextField();
        tf_sale = new javax.swing.JTextField();
        combo_piece = new javax.swing.JComboBox();
        combo_glass_type = new javax.swing.JComboBox();
        tf_brand = new javax.swing.JTextField();
        tf_sph = new javax.swing.JTextField();
        tf_cyl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        glass_table = new javax.swing.JTable();
        add_product_button = new javax.swing.JButton();
        product_update_button = new javax.swing.JButton();
        delete_product_button = new javax.swing.JButton();
        save_to_db_button = new javax.swing.JButton();
        show_db_button = new javax.swing.JButton();

        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setMinimumSize(new java.awt.Dimension(990, 525));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Glass Stock Operations");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Glass Type");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Brand :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Sph :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cyl :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Purchase Price");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Sale Price");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Piece");

        message_box.setForeground(new java.awt.Color(255, 0, 0));

        combo_piece.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        combo_glass_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Antirefle", "Colormatic", "Mineral-Organic", "Policarbonate", "Varilux(Multifocal)" }));

        glass_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Glass Type", "Brand", "Sph", "Cyl", "Piece", "Purchase Price", "Sale Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        glass_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                glass_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(glass_table);
        if (glass_table.getColumnModel().getColumnCount() > 0) {
            glass_table.getColumnModel().getColumn(0).setResizable(false);
            glass_table.getColumnModel().getColumn(1).setResizable(false);
            glass_table.getColumnModel().getColumn(2).setResizable(false);
            glass_table.getColumnModel().getColumn(3).setResizable(false);
            glass_table.getColumnModel().getColumn(4).setResizable(false);
            glass_table.getColumnModel().getColumn(5).setResizable(false);
            glass_table.getColumnModel().getColumn(6).setResizable(false);
        }

        add_product_button.setText("Add Product");
        add_product_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_product_buttonActionPerformed(evt);
            }
        });

        product_update_button.setText("Product Update");
        product_update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_update_buttonActionPerformed(evt);
            }
        });

        delete_product_button.setText("Delete Product");
        delete_product_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_product_buttonActionPerformed(evt);
            }
        });

        save_to_db_button.setText("Save to Database");
        save_to_db_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_to_db_buttonActionPerformed(evt);
            }
        });

        show_db_button.setText("Show the database");
        show_db_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_db_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(combo_glass_type, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tf_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tf_sph, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tf_cyl, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel7)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(tf_sale, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combo_piece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(message_box, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add_product_button)
                                .addGap(18, 18, 18)
                                .addComponent(product_update_button)
                                .addGap(18, 18, 18)
                                .addComponent(delete_product_button))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(save_to_db_button, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(show_db_button, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(combo_glass_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tf_sph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tf_cyl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_sale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_piece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(message_box, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_product_button)
                    .addComponent(product_update_button)
                    .addComponent(delete_product_button))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save_to_db_button)
                    .addComponent(show_db_button))
                .addContainerGap(58, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_product_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_product_buttonActionPerformed
        message_box.setText("");
        DefaultTableModel model = (DefaultTableModel) glass_table.getModel();
        if(tf_brand.getText().trim().equals("") || tf_sph.getText().trim().equals("") || tf_cyl.getText().trim().equals("") || tf_purchase.getText().trim().equals("") || tf_sale.getText().trim().equals("")){
            message_box.setText("Please fill all fields.");
        }
        else{
            Object[] eklenecek = {combo_glass_type.getSelectedItem().toString(),tf_brand.getText(),tf_sph.getText(),tf_cyl.getText(),combo_piece.getSelectedItem().toString(),tf_purchase.getText(),tf_sale.getText()};
                
            model.addRow(eklenecek);
        }
    }//GEN-LAST:event_add_product_buttonActionPerformed

    private void product_update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_update_buttonActionPerformed
       message_box.setText("");
        DefaultTableModel model = (DefaultTableModel) glass_table.getModel();
        
        int secili_row = glass_table.getSelectedRow();
        if(secili_row == -1){
            if(glass_table.getRowCount() == 0){
                message_box.setText("Product table is empty.");      
            }
            else{
                message_box.setText("Please select a product to update.");
            }
        }
        else{
            model.setValueAt(combo_glass_type.getSelectedItem().toString(),secili_row,0);
            model.setValueAt(tf_brand.getText(),secili_row,1);
            model.setValueAt(tf_sph.getText(),secili_row,2);
            model.setValueAt(tf_cyl.getText(),secili_row,3);
            model.setValueAt(combo_piece.getSelectedItem().toString(),secili_row,4);
            model.setValueAt(tf_purchase.getText(),secili_row,5);
            model.setValueAt(tf_sale.getText(),secili_row,6);
            message_box.setText("The product has been successfully updated.");
            
        }
    }//GEN-LAST:event_product_update_buttonActionPerformed

    private void glass_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glass_tableMouseClicked
       DefaultTableModel model = (DefaultTableModel) glass_table.getModel();
       message_box.setText("");
       int secili_row = glass_table.getSelectedRow();
       combo_glass_type.setSelectedItem(model.getValueAt(secili_row,0).toString());
       tf_brand.setText (model.getValueAt(secili_row,1).toString());
       tf_sph.setText (model.getValueAt(secili_row,2).toString());
       tf_cyl.setText (model.getValueAt(secili_row,3).toString());
       combo_piece.setSelectedItem(model.getValueAt(secili_row,4).toString());
       tf_purchase.setText (model.getValueAt(secili_row,5).toString());
       tf_sale.setText (model.getValueAt(secili_row,6).toString());
    }//GEN-LAST:event_glass_tableMouseClicked

    private void delete_product_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_product_buttonActionPerformed
        message_box.setText("");
        DefaultTableModel model = (DefaultTableModel) glass_table.getModel();
        
        int secili_row = glass_table.getSelectedRow();
        if(secili_row == -1){
            if(glass_table.getRowCount() == 0){
                message_box.setText("Product table is empty.");
            }
            else{
                message_box.setText("Please select a product to delete.");
            }
        }
        else{
            model.removeRow(secili_row);
            message_box.setText("The product has been successfully deleted.");
        }
    }//GEN-LAST:event_delete_product_buttonActionPerformed

    private void save_to_db_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_to_db_buttonActionPerformed
        message_box.setText("");
        int row = glass_table.getSelectedRow();
        if(row == -1){
            message_box.setText("Please select a row to save to database.");
        }
        else{
        String type = combo_glass_type.getSelectedItem().toString();
        String brand = tf_brand.getText();
        String sph = tf_sph.getText();
        String cyl = tf_cyl.getText();
        String piece = combo_piece.getSelectedItem().toString();
        String purchase = tf_purchase.getText();
        String sale = tf_sale.getText();
        
        islem.camEkle(type,brand,sph,cyl,piece,purchase,sale);
        message_box.setText("Saved to database successfully.");
        }
        
    }//GEN-LAST:event_save_to_db_buttonActionPerformed

    private void show_db_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_db_buttonActionPerformed
        DatabaseTable databaseTable = new DatabaseTable();
        databaseTable.setVisible(true);
        islem2.camGoruntule();
        
    }//GEN-LAST:event_show_db_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlassOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlassOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlassOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlassOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlassOperations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_product_button;
    private javax.swing.JComboBox combo_glass_type;
    private javax.swing.JComboBox combo_piece;
    private javax.swing.JButton delete_product_button;
    private javax.swing.JTable glass_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel message_box;
    private javax.swing.JButton product_update_button;
    private javax.swing.JButton save_to_db_button;
    private javax.swing.JButton show_db_button;
    private javax.swing.JTextField tf_brand;
    private javax.swing.JTextField tf_cyl;
    private javax.swing.JTextField tf_purchase;
    private javax.swing.JTextField tf_sale;
    private javax.swing.JTextField tf_sph;
    // End of variables declaration//GEN-END:variables
}
